export const ADD_NEW_RULE_RULE_GROUP = "ADD_NEW_RULE_RULE_GROUP";
export const ADD_NEW_RULE_GROUP = "ADD_NEW_RULE_GROUP";
export const DELETE_SPECIFIC_RULE_RULE_GROUP =
  "DELETE_SPECIFIC_RULE_RULE_GROUP";
export const DELETE_SPECIFIC_RULE_GROUP = "DELETE_SPECIFIC_RULE_GROUP";
export const DISPLAY_LIST_ADD_NEW_RULE = "DISPLAY_LIST_ADD_NEW_RULE";
export const DISPLAY_LIST_ADD_NEW_RULE_GROUP =
  "DISPLAY_LIST_ADD_NEW_RULE_GROUP";
export const DISPLAY_LIST_DELETE_SPECIFIC_RULE =
  "DISPLAY_LIST_DELETE_SPECIFIC_RULE";
export const DISPLAY_LIST_DELETE_SPECIFIC_RULE_GROUP =
  "DISPLAY_LIST_DELETE_SPECIFIC_RULE_GROUP";
export const ADD_TOGGLE_STATE = "ADD_TOGGLE_STATE";
export const REMOVE_TOGGLE_STATE = "REMOVE_TOGGLE_STATE"
export const UPDATE_TOGGLE_STATE = "UPDATE_TOGGLE_STATE"
export const UPDATE_QUERY_LIST = "UPDATE_QUERY_LIST"